---
- name: Install GitLab
  hosts: gitlab
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - openssh-server
          - ca-certificates
        state: present
        update_cache: yes

    - name: Add GitLab package repository
      apt_repository:
        repo: 'deb https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/ focal main'
        state: present

    - name: Install GitLab package
      apt:
        name: gitlab-ee
        state: latest

    - name: Configure GitLab
      command: gitlab-ctl reconfigure

    - name: Start GitLab service
      service:
        name: gitlab-runsvdir
        state: started
        enabled: yes
