---
- name: Install GitLab
  hosts: gitlab
  become: yes
  vars_file:
    - main.yml
    
  tasks:
    - name: Install required packages
      apt:
        name: "{{ required_packages }}"
        state: present
        update_cache: yes

    - name: Add GitLab package repository
      apt_repository:
        repo: "{{ gitlab_repo_url }}
        {{ gitlab_repo_distribution }}
        {{ gitlab_repo_component }}"
        state: present

    - name: Install GitLab package
      apt:
        name: "{{ gitlab_package }}"
        state: latest

    - name: Configure GitLab
      command: gitlab-ctl reconfigure

    - name: Start GitLab service
      service:
        name: gitlab-runsvdir
        state: started
        enabled: yes
